### PR TITLE
removed unnecessary args in checkSiaPath

### PR DESCRIPTION
**Pull request by eddiewang**
The siadConfig.path was being passed into a Promise that doesn't take arguments. Should work with it removed.

### CODE REVIEW

**Comment by avahowell** [comment]
5000+ diff lol, remove package-lock.json pls

**Comment by eddiewang** [comment]
Added the gitignore line as well

**Comment by lukechampine** [comment]
Please rebase c823df3 so that package-lock.json does not appear in the commit history.

**Comment by eddiewang** [comment]
I must have screwed something up. I'll just make another branch.

**Pull request closed without merging**
