### PR TITLE
Add a 'Stop Siad' button to the UI

### PR DESCRIPTION
**Pull request by avahowell**
screen shot 2016-07-06 at 6 17 19 pm

### CODE REVIEW

**Comment by DavidVorick** [comment]
LGTM

**Comment by lukechampine** [comment]
Do we need to feature the button so prominently? I feel like stopping siad is a pretty uncommon use case. You can stop siad from the Terminal, right?

**Comment by DavidVorick** [comment]
I've had multiple users requests a stop button. Do you feel that the stop button detracts from the overall look and feel / user experience?

**Comment by lukechampine** [comment]
Did they explain why they want it? What is the root problem that this addresses? Are there better ways we can solve this problem?
I think for most users, it's just a confusing new button. How many UI users really understand the relationship between the UI and siad? Many client-daemon apps don't expose that. Does any torrent client have a button that stops the daemon, but leaves the UI open? It just seems weird to me.

**Comment by droghio** [comment]
Is there anyway to restart siad with the default ui preferences once it stops?

**Comment by avahowell** [comment]
@droghio the current behavior (introduced by #355) is to start sia-ui with the current UI preferences (`config.js`)

**Comment by DavidVorick** [comment]
@lukechampine some users want to close the GUI but leave 'siad' running, while others want siad to shutdown when they close the GUI. We've had a lot of trouble finding the right balance between the two.

**Comment by WaveringAna** [comment]
You can have minimize be the close while keeping siad open and the exit as close both

**Comment by avahowell** [comment]
@aayanl this is actually already the case; closing the UI minimizes it to your system tray.  You can use the system tray to exit.

**Comment by DavidVorick** [comment]
@johnathanhowell are you planning on getting this PR ready to merge?

**Comment by avahowell** [comment]
I don't think a `Stop Siad` button really makes sense.  There should only be a quit button, and that already exists in the system tray.  I think a 'Stop Siad' button exposes implementation details to the user that they shouldn't care about.

**Comment by DavidVorick** [comment]
should this PR be closed then?

**Comment by avahowell** [comment]
yes.

**Pull request closed without merging**
