### PR TITLE
Packager

### PR DESCRIPTION
**Pull request by Mingling94**
In place of #111 should be reviewed after #114 
- Renamed `app` to `lib`
- Uses electron-packager.
- Tested on Linux and works.
- Imports siad from Gopath `bin` folder on release.
- IMPORTANT: Apparently for the icon to work on windows and the packager to work for windows release ran from Linux, wine has to be installed.

### CODE REVIEW

**Comment by lukechampine** [comment]
definitely looks like an improvement to me :+1:

**Comment by DavidVorick** [comment]
merge conflicts

**Comment by Mingling94** [comment]
@DavidVorick bloop

**Comment by DavidVorick** [comment]
need to delete resources/default_app from the release

I also think you don't need resources/atom.asar, not 100% sure on that though

You should also include 'siac' in the Sia/ folder, not just 'siad'.

Otherwise looks good

**Comment by Mingling94** [comment]
I had to add a .sh to do the default_app removal as it looked ugly in the package.json

**Comment by DavidVorick** [comment]
also, you should zip everything up. The linux ones should be put in a '.tar.gz' and everything else should be put in a '.zip'

**Comment by Mingling94** [comment]
https://github.com/loopline-systems/electron-builder#how-we-use-it-so-far to make installers is perhaps the next step

**Pull request merged**
