### PR TITLE
Remove screen header

### PR DESCRIPTION
**Pull request by pmknutsen**
This proposal is inspired by @irontiga's PR that removes the screen header and moves the update icons to the sidebar.

Changes:
- Remove screen header
- Move update icons to sidebar (show only when there is an update)

screenshot from 2016-01-23 23 39 53
screenshot from 2016-01-23 23 39 26

### CODE REVIEW

**Comment by lukechampine** [comment]
Update buttons in the sidebar feel a bit... overbearing.
Maybe we could move them inside the About plugin? Or only display them as a startup notification.
Also, `Update Sia` hasn't been functioning for a while now, so it can be removed entirely.

By the way, @Jinglan is currently designing a new look for the UI. Not sure how drastic her changes will be, but it might be best to hold off on further layout changes -- it'd be a shame to have to throw them away if they conflict with her designs. I'd like her to weigh in on this.

**Comment by DavidVorick** [comment]
I don't really like this change.

**Comment by pmknutsen** [comment]
In any case, for future consideration I think the top header needs to go if it will remain empty. Should I close this PR?

**Comment by DavidVorick** [comment]
waiting for comments from Jing, our designer.

**Comment by Jinglan** [comment]
I think better to have "notifications" between "wallet" and "about" on the sidebar, so you can click on "notifications" and see "New notification: UI update pending" or something like that.

**Comment by lukechampine** [comment]
While we aren't going to merge this outright, I think this layout may influence our future design.

**Pull request closed without merging**
