### PR TITLE
add pagination to the wallet transaction list

### PR DESCRIPTION
**Pull request by avahowell**
This PR adds pagination the wallet transaction list.

sia
sia2
sia3

### CODE REVIEW

**Comment by DavidVorick** [comment]
What happened to the date? Is this branch not up to date? We should make sure that the pagination code works with the date code. I mean, I'm pretty sure it will be fine but best to be prudent.

**Comment by avahowell** [comment]
The timestamp PR has not been merged into master yet

**Comment by DavidVorick** [comment]
ah, sorry. Merged now.

**Comment by avahowell** [comment]
Rebased with the time-stamping changes, should be ready to merge

**Pull request merged**
