### PR TITLE
add init from seed to uninitialized wallet screen

### PR DESCRIPTION
**Pull request by avahowell**
This PR adds the ability for users to initialize their wallet from a seed, on the uninitialized wallet screen
sia1
sia2
sia3
sia4

### CODE REVIEW

**Comment by DavidVorick** [comment]
If you init from seed, do you need a password, or are you setting a password?

**Comment by avahowell** [comment]
You can optionally provide a password (I tried to show that behavior in the screenshots) using the checkbox

**Comment by DavidVorick** [comment]
Ah. Text should be 'Desired Password'

**Comment by avahowell** [comment]
/init/seed can take a long time, this needs longer timeouts and some status feedback. Working on that now

**Comment by avahowell** [comment]
Should be ready now

**Comment by lukechampine** [comment]
Looks good but perhaps could use some more description. Users should understand that init-from-seed has to scan the whole blockchain, so it's slow and requires you to be synced.

**Comment by avahowell** [comment]
updated with some text: 
sia1

**Pull request merged**
