### PR TITLE
Restructured to accomodate David's design plans

### PR DESCRIPTION
**Pull request by Mingling94**
There is a package.json in the app folder, it does nothing besides
allow electron to run the app folder. The package.json in the top
level directory is for devdependencies only and allows one to run
makefile scripts OR npm scripts to run the program.

Currently only makefile scripts package up the program.

### CODE REVIEW

**Comment by DavidVorick** [comment]
Is there a way to configure the linter to favor tabs?

**Comment by DavidVorick** [comment]
http://www.reddit.com/r/javascript/comments/2d8729/jslint_or_jshint/cjn27ff

looks like we actually want jshint.

For me, tabs vs. spaces is a dealbreaker, as our entire codebase uses tabs. There are some other very strict rules as well.

**Comment by Mingling94** [comment]
Newest commit uses jshint in a strict way, allows tabs though.

**Comment by DavidVorick** [comment]
Is this ready  to be merged?

**Comment by Mingling94** [comment]
Yep! It's working and I haven't found it to be broken in any way.

**Pull request merged**
