### PR TITLE
Renter 'Buy Storage' UX improvements

### PR DESCRIPTION
**Pull request by avahowell**
This PR addresses the UX problems mentioned in issues #333, #330, and #328. Since host prices are volatile and subject to change, presenting the user with 'storage plans' by estimating the storage available from a certain allowance leads to all of these unexpected behaviors. Estimating the user's remaining storage is subject to the same problem. This has been addressed by removing the leaky 'Buy Storage' and 'Storage Available' abstractions; now the user is directly asked for an allowance to set and usage is reported as 'x SC spent / x SC allocated'.

In addition, a 'contractor status' component has been added, which displays the number of contracts the renter currently has, or a 'Forming Contracts...' loading spinner if the renter is currently setting the user's allowance.

Screenshots:
sia1
sia2
sia3
sia6
sia8

### CODE REVIEW

**Comment by VoidingWarranties** [comment]
We spent so much time working on the leaky abstraction and now we're getting rid of it 😭

It seems like the leaky abstraction is sinking like the Titanic. Overall I think this is a great change. It might be jarring for new users, but it's not like SC spent / SC allocated is too difficult to understand.

My only concern is that now a user has no sense of how many SC they should allocate when they buy storage. Perhaps we should show them a little helper text saying something like "The market price for 10GB is x SC right now (but the market is volatile and blah blah blah)"

**Comment by avahowell** [comment]
Latest commit adds storage estimation as a footnote to the 'buy storage' screen:

sia-estimate

**Comment by lukechampine** [comment]
Agreed, the purpose of the leaky abstraction was to frame things in terms of storage rather than money.
Actually, showing only the storage cost may be misleading, since download cost usually exceeds storage cost. It's just a hard thing to estimate unless you know the user's usage patterns. :|

**Comment by avahowell** [comment]
Note that the 'Spent' cost which is shown is the sum of upload, download, and storage spending.

**Comment by pmknutsen** [comment]
I find the wording in the input dialog a bit confusing, where it says "... After 12 weeks the contractor will renew the contracts it forms.". This seems to imply that funds will be automatically withdrawn from the wallet after 12 weeks, but I was under the impression that renewal of storage contracts is something the user always has to initiate (unlike files, which are automatically renewed)?

Also, I would avoid terms such as "contractor" as few non-power users will have any idea what that is. It would be sufficient to say "Sia".

**Comment by DavidVorick** [comment]
Also needs to mention fees.

"Before you can upload to Sia, you have to form contracts with the hosts. This creates a pool of money you can spend on uploading and downloading. Funds stay in the pool for 3 months. Funds not spent after 3 months will be returned to your wallet. Fees will not be returned.

The pool will refill automatically every 6 weeks, using the full 3 month budget. You will pay the fees again. Your computer must be online to refill the allowance, and if the allowance is unable to refill before the pool expires, you will lose all of your data."

Set Storage Allowance: [ 5000 SC]
Estimated Fees: 1600 (1000 + 0.12 \* allowance)

Estimated Prices:

Upload: 100 SC / GB
Download: 2500 SC / GB
Storage: 800 SC / GB / Mo

(or whatever the prices are)

**Comment by DavidVorick** [comment]
Should there be a progress bar for the 'spent' vs. 'allocated' part?

**Comment by avahowell** [comment]
Perhaps. If we did that, I'd want to have a tooltip that shows the numbers as well.

Screenshot of the latest iteration:
newbuystorage

**Comment by pmknutsen** [comment]
@DavidVorick I found the text a bit too technical (and unclear):

"You need to allocate funds for uploading to Sia. Your storage allowance remains locked for 3 months. Unspent funds are then refunded*. You can add funds to your allowance later.

Your storage allowance automatically refills every 6 weeks, up to your total storage allowance. Your computer must remain online, and the wallet unlocked, to complete automatic refills. If Sia fails to refill the allowance by the end lock-in period, your storage contracts will not be renewed and you risk loosing some or all of your data.
- transaction fees are non-refundable."

@johnathanhowell Can you increase the margins of the dialog?

**Comment by DavidVorick** [comment]
Also, dialogs with that much text should be left-aligned. The paragraph should be centered with padding but within the paragraph the text should be left-aligned.

**Comment by DavidVorick** [comment]
I like the text by @pmknutsen more than my own text, but still seems like it could use some work. @lukechampine perhaps you want to take a stab?

**Comment by lukechampine** [comment]
I like @pmknutsen's copy too, although I would make it more clear that the funds are used for bandwidth as well as storage costs (also: loosing -> losing). Perhaps some of the minor details (like the transaction fees bit) could be moved to a tooltip to prevent overwhelming the user with information.

**Comment by DavidVorick** [comment]
"You need to allocate funds to upload and download on Sia. Your allowance remains locked for 3 months. Unspent funds are then refunded*. You can increase your allowance at any time.

Your storage allowance automatically refills every 6 weeks. Your computer must be online with your wallet unlocked to complete the refill. If Sia fails to refill the allowance by the end lock-in period, your data may be lost.

*contract fees are non-refundable."

definitions note for support team - "contract fees" -> transaction fee (scales with transaction size) + contract fee (fee paid per host for forming contracts) + siafund fees (0.39% of storage + collateral)

**Comment by pmknutsen** [comment]
"...by the end lock-in period" should be "...by the end of the lock-in period"

**Comment by avahowell** [comment]
updated with the new copy, along with some minor styling changes. Here's the screenshot:

sia

**Comment by avahowell** [comment]
Should the User be prevented from setting an allowance if an allowance is currently in the process of being set (ie: the UI is displaying "Forming contracts...")? I was thinking it would probably be advisable to disable the 'Buy Storage' button while contracts are being formed. Also, does 'Buy Storage' still make sense as a name for the button, now that the user is directly setting their allowance?

**Comment by DavidVorick** [comment]
Margins should be maybe 2x as large, and the asterisk text should be slightly smaller, and it should be left-aligned with the other paragraphs. The spacing between the paragraphs should probably be reduced.

I think it makes sense to prevent the user from setting an allowance while contracts are being formed. Might annoy them because it can take up to 30 minutes to form contracts, but it'll prevent some potential headaches for the renter, which may not safely handle such an event.

Probably 'Set Allowance' or 'Create Allowance' or 'Update Allowance'

The Estimated Fees / Estimated Storage based on current prices should be tabular, such that the numbers align. Within the cells, text should be left-aligned and values should be right-aligned. I think I'm in favor of displaying the rows "Fees / Cost of Storage / Cost to Download", and then factor the cost of uploading into the cost of storage.

I also think the current visual for the set-allowance field could use work. I'm not sure how to fix it but it currently feels cluttered.

**Comment by avahowell** [comment]
Updated with most recent review comments:

sia

**Comment by pmknutsen** [comment]
Add some space between the input field and SC.

Also, its not clear if Estimated Fees are included in the allowance set by the user, or if they come in addition.

**Comment by avahowell** [comment]
Added spacing, clarified where the fees are paid, and changed the estimation table to be horizontal as @DavidVorick suggested offline:

sia

**Pull request merged**
