### PR TITLE
Minimum window size

### LINKED ISSUE #17: Allow Sia-UI window size to change

### PR DESCRIPTION
**Pull request by zlalvani**
I added two lines to the BrowserWindow parameters specifying a minimum window size of 800 x 600. 

fixes #17

### CODE REVIEW

**Comment by seveibar** [comment]
Hmm, for consistency, could you change 

```javascript
mainWindow = new BrowserWindow({
       width: 1200,
       height: 800,
       "min-width": 800,
       "min-height": 600,
       title: "Sia"
});
```
to

```javascript
mainWindow = new BrowserWindow({
       "width": 1200,
       "height": 800,
       "min-width": 800,
       "min-height": 600,
       "title": "Sia"
});
```

Thanks!

**Comment by zlalvani** [comment]
Done.

**Comment by zlalvani** [comment]
Done.

**Comment by seveibar** [comment]
Awesome thanks!

**Pull request merged**
