### PR TITLE
Add individual file upload on Windows and Linux

### PR DESCRIPTION
**Pull request by droghio**
Fixes issue #341.

### CODE REVIEW

**Comment by avahowell** [comment]
👍

tests would be helpful for this, did you test the behavior manually?  We can mock the `fs` calls using [rewire](https://github.com/jhnns/rewire), mocking `SiaAPI` is as simple as defining a `global.SiaAPI` in the test script.

**Comment by droghio** [comment]
I tested the behavior on Windows/Mac up until it sends the post call to the api. I might setup a test net to confirm the uploads are working as expected. I think we might be able to just get ride of the folder upload button all together, as long as people can select multiple files/drag and drop. I'll work on tests in the mean time.

**Comment by avahowell** [comment]
You don't need to test the entire upload process, only that this component has the expected behaviour (it calls uploadFolder with the selected folder(s) (if it's a folder), uploadFile with the selected file(s), dispatches the expected actions, etc)

**Comment by avahowell** [comment]
LGTM

**Pull request merged**
