### PR TITLE
replace instances of `fs` with `graceful-fs`

### PR DESCRIPTION
**Pull request by avahowell**
This PR completes Sia-UI's migration to `graceful-fs`.

### CODE REVIEW

**Comment by DavidVorick** [comment]
Not sure if I missed a bunch of PRs but can you explain what the difference is?

**Comment by DavidVorick** [comment]
nvm, I see that it's a drop-in replacement.

**Comment by DavidVorick** [comment]
https://github.com/isaacs/node-graceful-fs

**Comment by avahowell** [comment]
Yeah, there was a PR previous to this that explained the benefits. Definitely something we want.

**Pull request merged**
