### PR TITLE
Adhered Comments To JSDoc standards

### PR DESCRIPTION
**Pull request by Mingling94**
I should figure how to do this, but putting these changes in one commit is
easier for now

Check out New-Sia-UI/jsdoc/Sia-UI/0.4.0/index.html! The JSDoc folder is an auto-generated documentation site. It probably shouldn't be incorporated in the repo in hindsight, but I'm not sure where to put it

### CODE REVIEW

**Comment by DavidVorick** [comment]
this is the least descriptive name for a PR I've ever seen.

Also, you add 134,295 lines of code in this PR. I think this it's what you wanted lol

**Comment by Mingling94** [comment]
Oh yo, so have you checked out the autogenerated documentation? What do you think?

**Comment by DavidVorick** [comment]
I'm not merging 100kloc lol. The html is terrible.

I think we're going to have to have the jsdoc be out-of-repo (IE generate it yourself).

That's how the godoc works.

**Comment by Mingling94** [comment]
Word, I'll take it out

**Comment by Mingling94** [comment]
It's out

**Pull request merged**
