### PR TITLE
add terminal support for init seed

### PR DESCRIPTION
**Pull request by avahowell**
Manually tested and verified this change is functional- the terminal plugin has no unit testing

### CODE REVIEW

**Comment by DavidVorick** [comment]
How much work to set up some testing?

**Comment by avahowell** [comment]
a lot: we would have to mock API calls, refactor a lot of the Terminal plugin's code, and either commit a `siac` binary to this repo or mock `siac`

**Comment by avahowell** [comment]
This should be good to go

**Comment by DavidVorick** [comment]
build is failing

**Pull request merged**
