### PR TITLE
Renting

### PR DESCRIPTION
**Pull request by DavidVorick**
This is Ming's PR, except I fixed the merge conflict.

### CODE REVIEW

**Comment by DavidVorick** [comment]
It does seem like the wallet plugin is having trouble.

`[6388:0829/150528:INFO:CONSOLE(154)] "Wallet plugin logged from bignumber.js(1209): Uncaught BigNumber Error: new BigNumber() number type has more than 15 significant digits: -1.754140471637751e+24", source: file:///home/david/dev/gopath/src/github.com/NebulousLabs/New-Sia-UI/app/js/pluginManager.js (154)`

**Comment by DavidVorick** [comment]
overall though the UI seems complete except for a few bugs and perhaps a few other minor adjustments.

**Comment by DavidVorick** [comment]
hosting also seems to be having trouble

**Comment by Mingling94** [comment]
What's the hosting trouble?

Also the BigNumber error is because a value is being returned as a number instead of a string.

**Comment by DavidVorick** [comment]
hosting trouble is also as the bignums. I'll look into the api and see if we forgot to make them strings anywhere

**Comment by DavidVorick** [comment]
the weird thing is that the overview isn't having troubles - it's parsing the balance correctly (returning 98.25) when the wallet is parsing the balance as 98.245859528362323320848 - not even close

**Comment by Mingling94** [comment]
That provides a lot more info, I'll check it out
Edit: nm David got it

**Comment by DavidVorick** [comment]
oh I think the wallet just isn't doing any rounding

**Comment by DavidVorick** [comment]
ok commas fixed

**Comment by lukechampine** [comment]
you didn't push lol

**Comment by DavidVorick** [comment]
man you're saying I actually have to push code now?

Things were easier in the 80's

**Comment by DavidVorick** [comment]
ok, I am happy with this. It works pretty well. Should be ready for release, though we should also merge the quickfixes to 'siad'.

**Pull request merged**
