### PR TITLE
Use system fonts

### PR DESCRIPTION
**Pull request by moimael**
This is the configuration used by Atom and also medium before. It will use the system font on Ubuntu, Gnome, KDE, Windows, MacOS.

Remove the Roboto font except for Terminal which uses the monospace variant.

### CODE REVIEW

**Comment by lukechampine** [comment]
can you provide screenshots?

**Comment by moimael** [comment]
Here is a screenshot on gnome:
https://pasteboard.co/72qfK22hF.png

**Comment by avahowell** [comment]
I like this change, but it might be controversial. @DavidVorick @lukechampine thoughts?

**Comment by lukechampine** [comment]
hmm. I like having a consistent look across all platforms. What's the main impetus for using system fonts?

**Comment by moimael** [comment]
It looks more like a system app and less like a website. But as johnatanhowell stated, this is a bit of a controversial topic. I just know that the first time I launched the app, it looked weird to me because of that.
Atom is doing that too, and I wasn't able to check but I guess slack is doing that too. Both apps look very sleek font wise on Linux and feel more like an actual app

**Pull request closed without merging**
