### PR TITLE
Reorganization

### PR DESCRIPTION
**Pull request by Mingling94**
Daemon.js isn't working in this but that's not important, the latest commit of reorganization/renaming is what I wanted to run past you, @DavidVorick

### CODE REVIEW

**Comment by DavidVorick** [comment]
for the time being I would like you to keep out the Sia readme + api docs.

**Comment by Mingling94** [comment]
That was a mistake of including the Sia repo in this one. I just wanted to have a siad in the folder structure to test with.

**Comment by DavidVorick** [comment]
it should be pretty easy to remove

**Comment by DavidVorick** [comment]
oh yeah, you've got the binaries too. 'git rm' is the command you should probably use. You should probably also use rebase, Luke or I can help you with that.

**Comment by Mingling94** [comment]
I'm closing this PR, look to #13

**Pull request closed without merging**
