### PR TITLE
User settable passwords

### PR DESCRIPTION
**Pull request by avahowell**
This PR adds a long-requested feature by the community: the ability to initialize a wallet in the UI using a user-input passphrase. Addresses #332.

Screenshots:

sia1
sia2
sia3

### CODE REVIEW

**Comment by lukechampine** [comment]
@DavidVorick we generally want to discourage people from supplying their own password, right? Perhaps instead of the design in this PR, we could make it a more difficult by having a little button or checkbox labeled "I want to use a custom password" that pops up the password entry field.

**Comment by DavidVorick** [comment]
We can probably fix the font sizes too some we're here.

Yes the default should be to receive a seed, with an option to add your own password instead if you hit a button.

**Comment by avahowell** [comment]
ACK, I will change the design to prioritize using a seed.

**Comment by avahowell** [comment]
Updated this PR to add a small checkbox under the 'create wallet' button, which enables the password form. If this button isn't checked, the wallet is initialized in the usual way. I also upped the font size for the seed and the password.

Screenshots:
sia1
sia2

**Comment by lukechampine** [comment]
lgtm although I always get a bit unnerved when I see my password printed in plaintext. Not sure how @DavidVorick feels about it, but I think I'd prefer to have it replaced with ***** or something

**Comment by DavidVorick** [comment]
Maybe display the first two and last one character? 

Also, I don't think we have an API test for creating a wallet with the encryption password. Before we merge this, can we merge a test in the Sia repo that:

1. Creates a wallet with an encryption password
2. Unlocks that wallet and uses it
3. Reboots
4. Unlocks the wallet and uses it
5. Makes sure the seed can be loaded into a new wallet correctly

**Comment by lukechampine** [comment]
@johnathanhowell we're thinking that something like this is best:

Security-wise it's kinda silly because the seed is in plaintext and that's much more important to protect, but seeing your password in plaintext is just unnerving.

**Comment by avahowell** [comment]
What do you think about displaying the password with a simple spoiler tag-style interface? (it shows up as a black line of text until you hover)

**Comment by lukechampine** [comment]
that sounds fine to me

**Comment by avahowell** [comment]
done

**Pull request merged**
